//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.Dialogs.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.Dialogs.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Unable to load the progress dialog animation: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnimationLoadErrorFormat {
            get {
                return ResourceManager.GetString("AnimationLoadErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The credential target may not be an empty string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CredentialEmptyTargetError {
            get {
                return ResourceManager.GetString("CredentialEmptyTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred acquiring credentials. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CredentialError {
            get {
                return ResourceManager.GetString("CredentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PromptForCredentialsWithSave has not been called or the credentials were modified after the call. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CredentialPromptNotCalled {
            get {
                return ResourceManager.GetString("CredentialPromptNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task dialog already has a non-custom button with the same type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DuplicateButtonTypeError {
            get {
                return ResourceManager.GetString("DuplicateButtonTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task dialog already has an item with the same id. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DuplicateItemIdError {
            get {
                return ResourceManager.GetString("DuplicateItemIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &quot;{0}&quot; could not be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve the root folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderBrowserDialogNoRootFolder {
            get {
                return ResourceManager.GetString("FolderBrowserDialogNoRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current operating system does not support glass, or the Desktop Window Manager is not enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlassNotSupportedError {
            get {
                return ResourceManager.GetString("GlassNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid filter string, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFilterString {
            get {
                return ResourceManager.GetString("InvalidFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The id of a task dialog item must be higher than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidTaskDialogItemIdError {
            get {
                return ResourceManager.GetString("InvalidTaskDialogItemIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The item is not associated with a task dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoAssociatedTaskDialogError {
            get {
                return ResourceManager.GetString("NoAssociatedTaskDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot change the id for a standard button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonCustomTaskDialogButtonIdError {
            get {
                return ResourceManager.GetString("NonCustomTaskDialogButtonIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The progress dialog is not shown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressDialogNotRunningError {
            get {
                return ResourceManager.GetString("ProgressDialogNotRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The progress dialog is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressDialogRunning {
            get {
                return ResourceManager.GetString("ProgressDialogRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A custom button or radio button cannot have an empty label. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogEmptyButtonLabelError {
            get {
                return ResourceManager.GetString("TaskDialogEmptyButtonLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cross-thread operation not valid: Task dialog accessed from a thread other than the thread it was created on while it is visible. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogIllegalCrossThreadCallError {
            get {
                return ResourceManager.GetString("TaskDialogIllegalCrossThreadCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task dialog item already belongs to another task dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogItemHasOwnerError {
            get {
                return ResourceManager.GetString("TaskDialogItemHasOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task dialog must have buttons. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogNoButtonsError {
            get {
                return ResourceManager.GetString("TaskDialogNoButtonsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task dialog is not current displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogNotRunningError {
            get {
                return ResourceManager.GetString("TaskDialogNotRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The task dialog is already being displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogRunningError {
            get {
                return ResourceManager.GetString("TaskDialogRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operating system does not support task dialogs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TaskDialogsNotSupportedError {
            get {
                return ResourceManager.GetString("TaskDialogsNotSupportedError", resourceCulture);
            }
        }
    }
}
